using System;
using System.Collections.Generic;
using System.Text;

namespace ARK_Backend.Core.Helpers
{
	public enum ErrorCode
	{
		INTERNAL_EXCEPTION = 99,

		USER_NOT_FOUND = 100,
		WRONG_CREDENTIALS = 101,
		USERNAME_IS_TAKEN = 102,
		EMAIL_IS_TAKEN = 103,
		WRONG_PARAMS = 104,
		ROLE_NOT_FOUND = 105,
		WRONG_WORKING_DAY_BOUNDS = 106,
		ANONYMOUS_EMPLOYEES_ROLE_NOT_FOUND = 107,
		PERSON_CARD_NOT_FOUND = 108,
		WRONG_TIME_BOUNDS = 109,
		READER_NOT_FOUND = 110,
		ROLE_DOESNT_BELONG_TO_BUSINESS_USER = 112,
		ROLE_IS_ANONYMOUS = 113,
		ROLE_ALREADY_EXISTS = 114,
		EMPLOYEE_ALREADY_EXISTS = 115,
		EMPLOYEE_NOT_FOUND = 116,
		READER_ALREADY_RESTRICTED = 117,
		READER_NOT_RESTRICTED = 118,
		PERSON_NOT_EMPLOYEE = 119,
		FILE_NOT_FOUND = 120
	}
}
